type AppColors = {
  white: string
  black: string
  primary: string
  subPrimary: string
  primaryFont: string
  secondaryFont: string
  graybackground: string
  bordercolor: string
  red: string
  border: string
  delBackground: string
  primaryLight: string
  greenborder: string
  cardicon: string
  price: string
  subFont: string
  modelBg: string
  alertBg: string
  alertIconBg: string
  alertBorder: string
  invoiceBtn: string
  darkThemeSub: string
  categoryTitle: string
  alertRed: string
  activeColor: string
  completeColor: string
  scheduleColor: string
  darkborder: string
  closeBg: string
  darkPurpal: string
  lightPurpal: string
  lightRed: string
  primaryBg: string
  subCategorytag: string
  darkBorderBlack: string
  dotPrimary: string
  bgDark: string
  darkFillBar: string
  darkText: string
  planNote: string
  dropDownColor: string
  planDot: string
  planLine: string
  round: string
  grayRound: string
  tagColor: string
  loader: string
  pink: string
  lightPink: string
  lightOrange: string
  lightGreen: string
  lightYellow: string
  railFillBackgroundColor: string
  loaderBackground: string
  loaderLightHighlight: string
  iconColor: string
  line: string
  darkLine: string,
  dotDark: string,
  border1: string,
  yellow: string,
  bgColor: string,
  value: string,
  value1: string,
  bgColor1: string,
  bgColor2: string,
  blueShade: string,
  toup: string,
  whiteopicity: string,
  gray: string;
  orange: string;
  setp: string;
  lightGray?: string;
  cream?: string
  mintCream: string;
  steelGray: string;
  brightRed: string;
  vividRed: string;
  darkCrimson: string;
  roseTint: string;
  darkPrimary: string;
  lightGreen1:string;
  rgb:string
}

const appColors: AppColors = {
  loaderBackground: '#E8E8E8',
  loaderLightHighlight: '#F2F8FC',
  white: '#fff',
  black: '#000',
  darkText: '#BCBCBC',
  primary: '#199675',
  darkFillBar: '#303E3A',
  dotPrimary: '#2F4841',
  lightYellow: '#FFF7E5',
  pink: '#ff00ff',
  lightPink: '#F2E5FF',
  subPrimary: '#C9E2DB',
  lightGreen: '#ECF4FB',
  primaryFont: '#1F1F1F',
  secondaryFont: '#8F8F8F',
  graybackground: '#F5F5F5',
  border: '#E9E9E9',
  delBackground: '#FFEDED',
  primaryLight: '#32A284',
  greenborder: '#8ECCBB',
  cardicon: '#E8F4F1',
  price: '#20B149',
  red: '#FF4B4B',
  alertRed: '#F33737',
  subFont: '#171C26',
  modelBg: 'rgba(0, 0, 0, 0.5)',
  railFillBackgroundColor: 'rgba(223, 236,233, 0.5)',
  bordercolor: '#E9E9E9',
  alertBg: '#F6E4E4',
  alertIconBg: '#F7D5D5',
  alertBorder: '#F8C5C5',
  invoiceBtn: '#E0E0E0',
  darkThemeSub: '#343434',
  categoryTitle: '#8CCBBA',
  activeColor: '#3F8FDA',
  completeColor: '#FFB400',
  scheduleColor: '#7F00FF',
  darkborder: '#474747',
  closeBg: '#CFCDC6',
  darkPurpal: '#C084FC',
  lightPurpal: '#F9F3FF',
  lightRed: '#FFEDED',
  primaryBg: '#DFECE9',
  subCategorytag: '#F0EAF6',
  darkBorderBlack: '#797D83',
  bgDark: '#272727',
  planNote: '#F5F6F7',
  dropDownColor: '#fafafa',
  planDot: '#47AB91',
  planLine: '#9DCFC2',
  round: '#1B8569',
  grayRound: '#D0D3D8',
  tagColor: '#E8F5F2',
  loader: '#EEEEEE',
  lightOrange: '#FEEBEB',
  iconColor: '#777777',
  line: '#C7CACF',
  darkLine: '#1A8065',
  dotDark: "#2F4841",
  border1: "#E9E9E9",
  yellow: '#ECB238',
  bgColor: '#FDF7EB',
  value: '#BADFD6',
  value1: '#E8F4F1',
  bgColor1: '#F8F8F8',
  bgColor2: '#FFF4F1',
  blueShade: '#47A1E5',
  toup: '#B7C7C4',
  whiteopicity: '#F1F7FE',
  gray: '#FCF9EA',
  orange: '#FF8367',
  setp: '#86909C',
  lightGray: "#F4F4F4",
  cream: '#FCF9EA',
  mintCream: '#EEFBF6',
  steelGray: '#86909C',
  brightRed: '#F14848',
  vividRed: '#FF4B4B',
  darkCrimson: '#B42D30',
  roseTint: '#F5D5D6',
  darkPrimary: '#0F453A',
  lightGreen1:"#C1E2DA",
  rgb:"rgba(211, 211, 211, 0.2)"
}
export default appColors
