export const login = 'driver/login'
export const register = 'driver/register'
export const verifyOtp = 'driver/verify-token'
export const mailLogin = 'driver/email/login'
export const FirebaseAuth = 'driver/firebase/auth'
export const fleetLogin = 'fleet/login'
export const fleetRegister = 'fleet/register'
export const fleetVerifyOtp = 'fleet/verify-token'
